In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/final_dataset.csv")
df.head()

,post_id,post_date,platform,hashtag,content_type,region,views,likes,shares,comments,engagement_level,year,month,engagement_score,engagement_growth,revival_label
0,Post_1,2022-01-13,TikTok,#challenge,Video,UK,4163464,339431,53135,19346,High,2022,1,4575376,NaN,0
1,Post_3,2022-01-07,Twitter,#challenge,Video,Brazil,3666211,327143,39423,36223,Medium,2022,1,4069000,-0.110674,0
2,Post_79,2022-01-27,Instagram,#challenge,Reel,USA,4219632,171996,5043,3436,Medium,2022,1,4400107,0.081373,0
3,Post_237,2022-01-21,YouTube,#challenge,Tweet,UK,1091635,198291,5604,31314,Medium,2022,1,1326844,-0.698452,0
4,Post_344,2022-01-21,Instagram,#challenge,Video,Canada,121735,293092,98179,41884,Low,2022,1,554890,-0.581797,0

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

features = df[["engagement_score", "year"]].copy()

scaler = StandardScaler()
scaled = scaler.fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42)
df["cluster"] = kmeans.fit_predict(scaled)

df[["hashtag","year","engagement_score","cluster"]].head(10)

      hashtag  year  engagement_score  cluster
0  #challenge  2022           4575376        0
1  #challenge  2022           4069000        0
2  #challenge  2022           4400107        0
3  #challenge  2022           1326844        1
4  #challenge  2022            554890        1
5  #challenge  2022           4741299        0
6  #challenge  2022            227100        1
7  #challenge  2022           3147459        1
8  #challenge  2022           3454379        1
9  #challenge  2022           1315769        1

In [3]:
df.to_csv("../data/clustered_data.csv", index=False)
print("✅ clustered_data.csv saved")

✅ clustered_data.csv saved